import{a as d,P as v}from"./assets/vendor-90405565.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))i(n);new MutationObserver(n=>{for(const s of n)if(s.type==="childList")for(const r of s.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&i(r)}).observe(document,{childList:!0,subtree:!0});function o(n){const s={};return n.integrity&&(s.integrity=n.integrity),n.referrerpolicy&&(s.referrerPolicy=n.referrerpolicy),n.crossorigin==="use-credentials"?s.credentials="include":n.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(n){if(n.ep)return;n.ep=!0;const s=o(n);fetch(n.href,s)}})();const p="https://app.ticketmaster.com/discovery/v2/",f="uHSLi07StIOlriMPxJGxUbSYsHDs6AFx";async function h(e,t){return(await d.get(`${p}events.json?apikey=${f}&page=${e}&keyword=${t}`)).data}async function b(e){return(await d.get(`${p}events.json?apikey=${f}&id=${e}`)).data}const L={totalItems:0,itemsPerPage:20,visiblePages:3,page:1,centerAlign:!1,firstItemClassName:"tui-first-child",lastItemClassName:"tui-last-child",template:{page:'<a href="#" class="tui-page-btn">{{page}}</a>',currentPage:'<strong class="tui-page-btn tui-is-selected">{{page}}</strong>',moveButton:'<a href="#" class="tui-page-btn tui-{{type}}"><span class="tui-ico-{{type}}">{{type}}</span></a>',disabledMoveButton:'<span class="tui-page-btn tui-is-disabled tui-{{type}}"><span class="tui-ico-{{type}}">{{type}}</span></span>',moreButton:'<a href="#" class="tui-page-btn tui-{{type}}-is-ellip"><span class="tui-ico-ellip">...</span></a>'}},l=new v("pagination",L),m=l.getCurrentPage();function E(e){l.reset(e)}l.on("afterMove",e=>{const t=e.page;u(t),console.log(t)});const g=document.querySelector(".form");let a="";g.addEventListener("submit",$);function $(e){e.preventDefault(),a=g.elements.searchInput.value.trim(),u(m,a)}const y=document.querySelector(".events-list");function k(e){const t=e.map(({name:o,id:i})=>`
  <li id="${i}">
  <p id="${i}">${o} </p>
  </li>`).join("");y.innerHTML=t}async function u(e,t){try{const o=await h(e,t);o.page.totalElements||alert("Not find"),e===1&&E(o.page.totalElements),k(o._embedded.events)}catch(o){console.error(o)}}u(m,a);const P=document.querySelector(".modal"),c=document.querySelector(".backdrop");y.addEventListener("click",S);function S(e){const t=e.target.id;t&&(c.classList.remove("is-hidden"),I(t))}function w(e){const t=`
<img src="${e[0].images[0].url}" width="200" height="200" />
<p>${e[0].name}</p>
<p>${e[0].info||""}</p>
`;P.innerHTML=t}async function I(e){try{const t=await b(e);console.log(t._embedded.events),w(t._embedded.events)}catch(t){console.error(t)}}c.addEventListener("click",()=>{c.classList.add("is-hidden")});
//# sourceMappingURL=commonHelpers.js.map
